import "./slider-demo/slider-demo__wrapper.scss"
import "./config-panel/config-panel__wrapper.scss"
import "./item/item__wrapper.scss"
import "./item/item__sign.scss"
import "./item/item__select.scss"
import "./item/item__input.scss"
import "./item/item__first-input.scss"
import "./item/item__second-input.scss"